### ISSUE TITLE
Got error while running sudo deauth command

### ISSUE THREAD

**Issue by huzaifamk** [Drew-Alleman/autodeauth#3]
**Describe the bug**
A clear and conciMatplotlib is building the font cache; this may take a moment.
Traceback (most recent call last):
  File "/usr/local/bin/autodeauth", line 21, in <module>
    from scapy.layers.dot11 import RadioTap, Dot11, Dot11Deauth
  File "/usr/local/lib/python3.11/dist-packages/scapy/layers/dot11.py", line 19, in <module>
    from scapy.ansmachine import *
  File "/usr/local/lib/python3.11/dist-packages/scapy/ansmachine.py", line 16, in <module>
    from scapy.sendrecv import send,sendp,sniff
  File "/usr/local/lib/python3.11/dist-packages/scapy/sendrecv.py", line 32, in <module>
    import scapy.route
  File "/usr/local/lib/python3.11/dist-packages/scapy/route.py", line 191, in <module>
    conf.route=Route()
               ^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/scapy/route.py", line 27, in __init__
    self.resync()
  File "/usr/local/lib/python3.11/dist-packages/scapy/route.py", line 34, in resync
    from scapy.arch import read_routes
  File "/usr/local/lib/python3.11/dist-packages/scapy/arch/__init__.py", line 25, in <module>
    from scapy.arch.bpf.core import get_if_raw_addr
  File "/usr/local/lib/python3.11/dist-packages/scapy/arch/bpf/core.py", line 29, in <module>
    LIBC = cdll.LoadLibrary(find_library("libc"))
                            ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ctypes/util.py", line 341, in find_library
    _get_soname(_findLib_gcc(name)) or _get_soname(_findLib_ld(name))
                ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ctypes/util.py", line 147, in _findLib_gcc
    if not _is_elf(file):
           ^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ctypes/util.py", line 99, in _is_elf
    with open(filename, 'br') as thefile:
         ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: b'liblibc.a'
se description of what the bug is.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by huzaifamk** [comment]
Fixed by this article:

https://stackoverflow.com/questions/65410481/filenotfounderror-errno-2-no-such-file-or-directory-bliblibc-a

**Comment by Drew-Alleman** [comment]
Hello,

Thanks for creating an issue request, and then posting the solution. You are greatly appreciated.

Best,
Drew Alleman
